export const products = [
    { id: 1, name: "Wireless Earbuds", category: "Electronics", price: 49.99, rating: 4.5, brand: "SoundPro", color: "Black", inStock: true, freeShipping: true },
    { id: 2, name: "Running Shoes", category: "Fashion", price: 89.99, rating: 4.2, brand: "RunFast", color: "Blue", inStock: true, freeShipping: false },
    { id: 3, name: "Smartphone", category: "Electronics", price: 599.99, rating: 4.8, brand: "Techie", color: "Silver", inStock: false, freeShipping: true },
    { id: 4, name: "Blender", category: "Home Appliances", price: 29.99, rating: 4.1, brand: "KitchenEase", color: "White", inStock: true, freeShipping: true },
    { id: 5, name: "Yoga Mat", category: "Fitness", price: 19.99, rating: 4.6, brand: "FitFlex", color: "Green", inStock: true, freeShipping: false },
    { id: 6, name: "Laptop", category: "Electronics", price: 899.99, rating: 4.7, brand: "CompTech", color: "Gray", inStock: false, freeShipping: true },
    { id: 7, name: "Wrist Watch", category: "Fashion", price: 129.99, rating: 4.3, brand: "TimeMax", color: "Black", inStock: true, freeShipping: true },
    { id: 8, name: "Electric Kettle", category: "Home Appliances", price: 24.99, rating: 4.2, brand: "HomeEssentials", color: "Silver", inStock: true, freeShipping: false },
    { id: 9, name: "Dumbbell Set", category: "Fitness", price: 39.99, rating: 4.4, brand: "PowerLift", color: "Black", inStock: true, freeShipping: false },
    { id: 10, name: "Graphic T-Shirt", category: "Fashion", price: 15.99, rating: 4.0, brand: "StyleWear", color: "Red", inStock: false, freeShipping: false },
    { id: 11, name: "Digital Camera", category: "Electronics", price: 349.99, rating: 4.6, brand: "PhotoPro", color: "Black", inStock: true, freeShipping: true },
    { id: 12, name: "Vacuum Cleaner", category: "Home Appliances", price: 79.99, rating: 4.1, brand: "CleanEase", color: "Blue", inStock: true, freeShipping: false },
    { id: 13, name: "LED TV", category: "Electronics", price: 499.99, rating: 4.7, brand: "ViewMax", color: "Black", inStock: false, freeShipping: true },
    { id: 14, name: "Water Bottle", category: "Fitness", price: 12.99, rating: 4.5, brand: "HydroFit", color: "Blue", inStock: true, freeShipping: true },
    { id: 15, name: "Leather Jacket", category: "Fashion", price: 199.99, rating: 4.6, brand: "LuxWear", color: "Brown", inStock: true, freeShipping: false },
    { id: 16, name: "Gaming Console", category: "Electronics", price: 299.99, rating: 4.8, brand: "GameBox", color: "Black", inStock: false, freeShipping: true },
    { id: 17, name: "Coffee Maker", category: "Home Appliances", price: 59.99, rating: 4.3, brand: "CafeBrew", color: "White", inStock: true, freeShipping: false },
    { id: 18, name: "Camping Tent", category: "Outdoor", price: 99.99, rating: 4.4, brand: "CampOut", color: "Green", inStock: true, freeShipping: true },
    { id: 19, name: "Handbag", category: "Fashion", price: 79.99, rating: 4.1, brand: "BagElegance", color: "Red", inStock: true, freeShipping: false },
    { id: 20, name: "Bluetooth Speaker", category: "Electronics", price: 39.99, rating: 4.5, brand: "SoundWave", color: "Gray", inStock: true, freeShipping: true },
    { id: 21, name: "Microwave Oven", category: "Home Appliances", price: 89.99, rating: 4.3, brand: "QuickHeat", color: "Silver", inStock: false, freeShipping: true },
    { id: 22, name: "Backpack", category: "Fashion", price: 49.99, rating: 4.4, brand: "TravelLight", color: "Black", inStock: true, freeShipping: false },
    { id: 23, name: "Indoor Bike", category: "Fitness", price: 159.99, rating: 4.6, brand: "CyclePro", color: "Gray", inStock: true, freeShipping: true },
    { id: 24, name: "Hair Dryer", category: "Home Appliances", price: 24.99, rating: 4.2, brand: "StyleEase", color: "Pink", inStock: true, freeShipping: false },
    { id: 25, name: "Sneakers", category: "Fashion", price: 69.99, rating: 4.5, brand: "StepRight", color: "White", inStock: true, freeShipping: true },
    { id: 26, name: "Fitness Tracker", category: "Electronics", price: 49.99, rating: 4.4, brand: "FitPro", color: "Black", inStock: false, freeShipping: true },
    { id: 27, name: "Espresso Machine", category: "Home Appliances", price: 129.99, rating: 4.6, brand: "BrewMaster", color: "Silver", inStock: true, freeShipping: false },
    { id: 28, name: "Beach Umbrella", category: "Outdoor", price: 34.99, rating: 4.3, brand: "SunShade", color: "Yellow", inStock: true, freeShipping: true },
    { id: 29, name: "Sunglasses", category: "Fashion", price: 29.99, rating: 4.2, brand: "ShadePlus", color: "Black", inStock: true, freeShipping: false },
    { id: 30, name: "Portable Charger", category: "Electronics", price: 19.99, rating: 4.5, brand: "ChargeFast", color: "Black", inStock: true, freeShipping: true },
  ];
  
  export const categories = ["Electronics", "Fashion", "Home Appliances", "Fitness", "Outdoor"];